---
on:
  push:
    branches:
      - "main"
    paths:
      - "bicep/**"
name: Azure Bicep Deployment

permissions: read-all

env:
  RGNAME: radapp
  LOCATION: eastus
  BICEPFILE: ./bicep/aks.bicep
  CLUSTERNAME: robcluster
  DNSPREFIX: robsworld

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@4c88f01b0e3a5600e08a37889921afd060f75cf0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        uses: azure/CLI@b0e31ae20280d899279f14c36e877b4c6916e2d3
        with:
          inlineScript: |
            az group create -n $RGNAME -l $LOCATION

        # Deploy Bicep file
      - name: Deploy AKS Cluster
        uses: azure/arm-deploy@65ae74fb7aec7c680c88ef456811f353adae4d06
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.RGNAME }}
          template: ${{ env.BICEPFILE }}
          parameters: >-
            sshRSAPublicKey="${{ secrets.AKSPUBKEY }}"
            clusterName=${{ env.CLUSTERNAME }}
            dnsPrefix=${{ env.DNSPREFIX }}
          failOnStdErr: false
